database:
  username: postgres
  password: admin
  port: 5432
  host: localhost
  database_name: scaffold
application:
  port: 8081
  host: 127.0.0.1
  hmac_secret: "jruqrqonaupqrthnfopdnhqporuebnlasht"
email_client:
  base_url: localhost
  sender_email: test@gmail.com
  authorization_token: my_secret_token
  timeout_milliseconds: 10000
